;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        go-mode-insert-and-indent
        ido-switch-buffer
        isearch-forward-regexp
        isearch-other-control-char
        isearch-repeat-forward
        sp--self-insert-command
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ido-find-file
        js2-mode-show-node
        tagedit-insert-gt
        tagedit-insert-lt
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))
