;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        company-indent-or-complete-common
        dired-unmark-backward
        go-mode-insert-and-indent
        ignore
        indent-for-tab-command
        paredit-forward-delete
        paredit-kill
        sgml-slash
        tern-ac-dot-complete
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        js2-mode-show-node
        kill-region
        markdown-exdent-or-delete
        mouse-save-then-kill
        mouse-set-region
        save-buffers-kill-emacs
        ))
