;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        indent-for-tab-command
        paredit-forward-delete
        paredit-kill
        sgml-slash
        tern-ac-dot-complete
        ))

(setq mc/cmds-to-run-once
      '(
        js2-mode-show-node
        kill-region
        mouse-set-region
        ))
